# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00ca31719a2b968dc6b634f73f9de8c57cbdcd455178e090bb2d8b481171eb78c3aa09b7d92c18c637f1b9a284907b3650759d9c06c4136f496c9c19f6ecf182

test:
  secret_key_base: f40a1f32c8659ee86cc15f37e42887dfd5ad43cf7fc781eb191573c80edca8d6ae2701a7f9c01d65f6e961ad47db6f0056ab16f7c43bfba6c38e995d6d2fe400

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
